** HEY **

- this is an item
- why I want to kill myself

$$\frac{1}{2}$$

In [8]:
import matplotlib as plt
import numpy as np
import pandas as pd

[[2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1.]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])